feat: support resource name for icon on windows
amrbashir/system_tray pull request #136
Opened 2024-04-08 13:36 UTC by mokurin000

2024-04-08 20:52 UTC, amrbashir requested changes
Thank you, left a couple of suggestions. You also need to add a change file in `.changes` directory

2024-04-08 20:52 UTC, amrbashir commented on src/icon.rs
> +    /// rather than oridinal id.
```suggestion
    /// This is basically the same as from_resource, but takes a resource name
    /// rather than oridinal id.
```

2024-04-08 20:52 UTC, amrbashir commented on src/platform_impl/windows/icon.rs
> +        let wide_name: Vec<u16> = name.encode_wide().collect();
```suggestion
        let wide_name= util::encode_wide(resource_name);
```

2024-04-09 00:57 UTC, mokurin000 commented
@amrbashir Hi! Thanks for having a look, I did the requested changes

2024-04-09 01:10 UTC, amrbashir commented on .changes/icon-resource-name.md
> +Support icon resource without a ordinal id on Windows
```suggestion
Add `Icon::from_resource_name` to support icon resource without a ordinal id on Windows
```

2024-04-09 01:11 UTC, amrbashir commented
seems like you also need to do `cargo fmt`

2024-04-09 01:29 UTC, amrbashir approved these changes

2024-04-09 01:42 UTC, merged