feat: Implement with_menu_on_left_click on windows
amrbashir/system_tray pull request #189
Opened 2024-08-29 09:20 UTC by htngr

Fixes https://github.com/tauri-apps/tauri/issues/7719 (for tauri 2.0)

2024-08-29 15:46 UTC, amrbashir requested changes
Thank you, could you add a change file in `.changes` directory?

2024-08-30 07:48 UTC, htngr commented
Done

2024-09-02 14:44 UTC, amrbashir commented on .changes/with_menu_on_left_click_windows.md
> +Implemented TrayIcon::with_menu_on_left_click on windows
```suggestion
Implemented `TrayIcon::with_menu_on_left_click` on windows
```

2024-09-02 14:44 UTC, amrbashir approved these changes
Thank you

2024-09-02 15:00 UTC, merged