feat: add set_icon_with_as_template
amrbashir/system_tray pull request #204
Opened 2024-11-06 13:52 UTC by mrexox

Closes https://github.com/tauri-apps/tray-icon/issues/203

I am not sure this is correct in 100% cases but it feels more natural that when you change the icon you want the similar settings for its `icon_is_template` value.

2024-11-12 00:52 UTC, amrbashir requested changes
`set_icon_as_template` was provided separately because it doesn't exist on other operating systems, this also doesn't fix usage DX that much because if you need to set a normal icon, you will have to 
```
tray.set_icon_as_template(false);
tray.set_icon(new_icon);
```
which IMO is worse than current API. 

I think we can instead add `set_icon_with_as_template` or something that allows the caller to specify both,

2024-11-19 15:09 UTC, mrexox commented
Adding a new method requires a contribution to the main Tauri repo, right?

2024-11-19 22:50 UTC, amrbashir commented
> Adding a new method requires a contribution to the main Tauri repo, right?

That's correct

2024-11-19 22:52 UTC, amrbashir requested changes
Could you also add a change file in `.changes` directory?

2024-11-19 22:52 UTC, amrbashir commented on src/platform_impl/macos/mod.rs
> +        self.attrs.icon = icon;
we need to also update `self.attrs.icon_is_template`
```suggestion
        self.attrs.icon = icon;
        self.attrs.icon_is_template = is_template;
```

2024-11-21 12:22 UTC, amrbashir approved these changes
Thank you

2024-11-21 12:22 UTC, merged